// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtiAKPg6uUU_VqcDUwHp2ngaMAsxzf3gA',
    appId: '1:402725284255:web:d6fa76ced2371c72f675aa',
    messagingSenderId: '402725284255',
    projectId: 'fashionshop-8a2e6',
    authDomain: 'fashionshop-8a2e6.firebaseapp.com',
    databaseURL: 'https://fashionshop-8a2e6-default-rtdb.firebaseio.com',
    storageBucket: 'fashionshop-8a2e6.appspot.com',
    measurementId: 'G-Q8PP96HKL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd_JPE7vggA50oLCJEgNEiw2qk-6QE_g0',
    appId: '1:402725284255:android:4f67817d66dfc6b3f675aa',
    messagingSenderId: '402725284255',
    projectId: 'fashionshop-8a2e6',
    databaseURL: 'https://fashionshop-8a2e6-default-rtdb.firebaseio.com',
    storageBucket: 'fashionshop-8a2e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAWSNYJUmQnWcsGWkp2AXDt3lui6oIzc8',
    appId: '1:402725284255:ios:b31a35fe3b010a17f675aa',
    messagingSenderId: '402725284255',
    projectId: 'fashionshop-8a2e6',
    databaseURL: 'https://fashionshop-8a2e6-default-rtdb.firebaseio.com',
    storageBucket: 'fashionshop-8a2e6.appspot.com',
    androidClientId: '402725284255-qss6v6e08djngp4luvbr627u7opns95d.apps.googleusercontent.com',
    iosClientId: '402725284255-g4e24486d8nna2rq8lugfmou5oin2kq3.apps.googleusercontent.com',
    iosBundleId: 'com.example.fashionShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAWSNYJUmQnWcsGWkp2AXDt3lui6oIzc8',
    appId: '1:402725284255:ios:b31a35fe3b010a17f675aa',
    messagingSenderId: '402725284255',
    projectId: 'fashionshop-8a2e6',
    databaseURL: 'https://fashionshop-8a2e6-default-rtdb.firebaseio.com',
    storageBucket: 'fashionshop-8a2e6.appspot.com',
    androidClientId: '402725284255-qss6v6e08djngp4luvbr627u7opns95d.apps.googleusercontent.com',
    iosClientId: '402725284255-g4e24486d8nna2rq8lugfmou5oin2kq3.apps.googleusercontent.com',
    iosBundleId: 'com.example.fashionShop',
  );
}
